### ISSUE TITLE
How to styling it, especialy i want to change padding size between stars

### ISSUE THREAD

**Issue by andriyfm** [SinanMtl/vue-rate#20]
I try to change the padding of Rate__star class, but i could not changed.
```
.Rate {
  button.Rate__star {
    padding: 0 !important;
  }
}

// or
.Rate {
  .Rate__star {
    padding: 0 !important;
  }
}

// or
button.Rate__star {
  padding: 0 !important;
}
```

**Comment by mmazga** [comment]
<style>
  .Rate__star {
    padding: 0 !important
  }
</style> Helped me

**Comment by SinanMtl** [comment]
Hi guys! You can customize style or icon with [v2.3.0](https://github.com/SinanMtl/vue-rate/releases/tag/v2.3.0) 🎊
