### ISSUE TITLE
can disable button just display

### ISSUE THREAD

**Issue by learnmove** [SinanMtl/vue-rate#3]
hope like be
<Rate :value='5' disabled></Rate>
 just show

**Comment by SinanMtl** [comment]
I got it. This feature will be ready soon. 👍🏻

**Comment by learnmove** [comment]
thanks you SinanMtl ,nice plugin

**Comment by SinanMtl** [comment]
Hey @learnmove, Vue Rate can disable now. You can see v1.2.0 changelog: https://github.com/SinanMtl/vue-rate/releases/tag/v1.2.0
