### ISSUE TITLE
Disabled form with yellow stars

### ISSUE THREAD

**Issue by ouraios** [SinanMtl/vue-rate#6]
It would be nice to have this features for display purpose
like " i want to input my rateand i want other to see it ", so not in a grey color for other to see it
Do you think that's possible ?

**Comment by SinanMtl** [comment]
Like read-only?

**Comment by SinanMtl** [comment]
@ouraios I added read-only feature. Check this out : https://sinanmtl.github.io/vue-rate/

**Comment by ouraios** [comment]
Yes exactly like read only !
That's great !
How can i use this features ??

**Comment by SinanMtl** [comment]
Readme updated :)
